# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fractal_gpt',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/fractal_gpt',
                'lib_path': 'annotatedGPT'},
  'syms': {'annotatedGPT.core': {'annotatedGPT.core.foo': ('core.html#foo', 'annotatedGPT/core.py')}}}
